id: ExtractURL-Test
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: ExtractURL-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 992a1aa0-984f-4815-8395-9eebef9750b5
    type: start
    task:
      id: 992a1aa0-984f-4815-8395-9eebef9750b5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 71c9cf88-bf0f-4af1-8050-0edfa5f53835
    type: regular
    task:
      id: 71c9cf88-bf0f-4af1-8050-0edfa5f53835
      version: -1
      name: Extract ATP URL
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      input:
        simple: https://na01.safelinks.protection.outlook.com/?url=hXXps%3A%2F%2Foffice.memoriesflower.com%2FPermission%2Foffice.php&data=01%7C01%7Cdavid.levin%40mheducation.com%7C0ac9a3770fe64fbb21fb08d50764c401%7Cf919b1efc0c347358fca0928ec39d8d5%7C0&sdata=PEoDOerQnha%2FACafNx8JAep8O9MdllcKCsHET2Ye%2B4%3D&reserved=0
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 8d896fc6-4397-4240-89f4-8bb18c4a19f1
    type: condition
    task:
      id: 8d896fc6-4397-4240-89f4-8bb18c4a19f1
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: URL
            iscontext: true
          right:
            value:
              simple: https://office.memoriesflower.com/Permission/office.php
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 197c87ec-d69e-4786-8100-2e35c58c80da
    type: regular
    task:
      id: 197c87ec-d69e-4786-8100-2e35c58c80da
      version: -1
      name: 'Extract Proof Point V1 URL '
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v1/url?u=meow://www.bouncycastle.org/&amp;k=oIvRg1%2BdGAgOoM1BIlLLqw%3D%3D%0A&amp;r=IKM5u8%2B%2F%2Fi8EBhWOS%2BqGbTqCC%2BrMqWI%2FVfEAEsQO%2F0Y%3D%0A&amp;m=Ww6iaHO73mDQpPQwOwfLfN8WMapqHyvtu8jM8SjqmVQ%3D%0A&amp;s=d3583cfa53dade97025bc6274c6c8951dc29fe0f38830cf8e5a447723b9f1c9a
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 93ee60d1-273c-4197-86b2-c6f40cc6a2d3
    type: condition
    task:
      id: 93ee60d1-273c-4197-86b2-c6f40cc6a2d3
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: URL
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: http://www.bouncycastle.org/
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 526bfc1a-3595-4c56-81af-3fef0b904520
    type: regular
    task:
      id: 526bfc1a-3595-4c56-81af-3fef0b904520
      version: -1
      name: Extract Proof Point V2 URL
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v2/url?u=http-3A__links.mkt3337.com_ctt-3Fkn-3D3-26ms-3DMzQ3OTg3MDQS1-26r-3DMzkxNzk3NDkwMDA0S0-26b-3D0-26j-3DMTMwMjA1ODYzNQS2-26mt-3D1-26rt-3D0&d=DwMFaQ&c=Vxt5e0Osvvt2gflwSlsJ5DmPGcPvTRKLJyp031rXjhg&r=MujLDFBJstxoxZI_GKbsW7wxGM7nnIK__qZvVy6j9Wc&m=QJGhloAyfD0UZ6n8r6y9dF-khNKqvRAIWDRU_K65xPI&s=ew-rOtBFjiX1Hgv71XQJ5BEgl9TPaoWRm_Xp9Nuo8bk&e=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: a5644d3c-7f1c-43a5-84a1-1461eb79e9dc
    type: condition
    task:
      id: a5644d3c-7f1c-43a5-84a1-1461eb79e9dc
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: URL
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: http://links.mkt3337.com/ctt?kn=3&ms=MzQ3OTg3MDQS1&r=MzkxNzk3NDkwMDA0S0&b=0&j=MTMwMjA1ODYzNQS2&mt=1&rt=0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 4a1f49d4-7cfe-42ef-88ff-adec3cb88a9d
    type: regular
    task:
      id: 4a1f49d4-7cfe-42ef-88ff-adec3cb88a9d
      version: -1
      name: Extract Proof Point V3 URL
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      input:
        simple: https://urldefense.com/v3/__https://google.com:443/search?q=a*test&gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 47ad7d2a-fdbd-48a9-8387-b1112343250f
    type: condition
    task:
      id: 47ad7d2a-fdbd-48a9-8387-b1112343250f
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: URL
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: https://google.com:443/search?q=a*test&gs=ps
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 4551bd2c-6ad9-4898-8f72-29caf7aaecd8
    type: regular
    task:
      id: 4551bd2c-6ad9-4898-8f72-29caf7aaecd8
      version: -1
      name: Extract Proof Point V3 Gov URL
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      input:
        simple: https://urldefense.us/v3/__https://google.com:443/search?q=a*test&gs=ps__;Kw!-612Flbf0JvQ3kNJkRi5Jg!Ue6tQudNKaShHg93trcdjqDP8se2ySE65jyCIe2K1D_uNjZ1Lnf6YLQERujngZv9UWf66ujQIQ$
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 3b29aec3-a8bb-4e4f-8965-9db598e42552
    type: condition
    task:
      id: 3b29aec3-a8bb-4e4f-8965-9db598e42552
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: URL
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: https://google.com:443/search?q=a*test&gs=ps
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 997c869c-e0a5-4abf-8339-a5fbf5a39304
    type: regular
    task:
      id: 997c869c-e0a5-4abf-8339-a5fbf5a39304
      version: -1
      name: Extract Test URL
      description: 'Formats URL to indicator: extracts redirect URL from Proof Point
        or ATP URLs. Strips and unquotes and unescapes URLs'
      scriptName: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      input:
        simple: https://www.test.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: e9f472ce-1b85-4c65-8514-0c30317b126d
    type: condition
    task:
      id: e9f472ce-1b85-4c65-8514-0c30317b126d
      version: -1
      name: Assert Expected URL is Extracted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: URL
                transformers:
                - operator: LastArrayElement
            iscontext: true
          right:
            value:
              simple: https://www.test.com
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 569ff6b4-bd7a-4c85-8650-6a55a19ac554
    type: title
    task:
      id: 569ff6b4-bd7a-4c85-8650-6a55a19ac554
      version: -1
      name: Playbook Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
