id: YodaSpeak_Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: YodaSpeak_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 637a7c4c-9fcd-442e-8c42-cce076e126f9
    type: start
    task:
      id: 637a7c4c-9fcd-442e-8c42-cce076e126f9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 0659dfab-124f-446f-860b-8fc91b700074
    type: regular
    task:
      id: 0659dfab-124f-446f-860b-8fc91b700074
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 16194870-ff41-4c27-8b35-3c9d1474ae0e
    type: regular
    task:
      id: 16194870-ff41-4c27-8b35-3c9d1474ae0e
      version: -1
      name: yoda-speak-translate
      script: YodaSpeak|||yoda-speak-translate
      type: regular
      iscommand: true
      brand: YodaSpeak
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      text:
        simple: Test playbooks are used to test integration functionality
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4e93960e-8e8d-44ac-823f-36e046cd8282
    type: condition
    task:
      id: 4e93960e-8e8d-44ac-823f-36e046cd8282
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: YodaSpeak
                accessor: Original
            iscontext: true
          right:
            value:
              simple: Test playbooks are used to test integration functionality
      - - operator: isEqualString
          left:
            value:
              complex:
                root: YodaSpeak
                accessor: Translation
            iscontext: true
          right:
            value:
              simple: Used to test integration functionality,  test playbooks are
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 08bedbb7-056c-4564-8228-44ab0e4f0b81
    type: title
    task:
      id: 08bedbb7-056c-4564-8228-44ab0e4f0b81
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
