comment: Entry widget that returns the number of rules with unused applications found
  by PAN-OS policy optimizer.
commonfields:
  id: d28068de-3331-46ad-8ed5-3910085b544a
  version: -1
dockerimage: demisto/python3:3.9.7.24076
enabled: true
engineinfo: {}
name: EntryWidgetUnusedApplications
pswd: ""
runas: DBotWeakRole
runonce: false
script: |2


  incident = demisto.incidents()
  no_apps = demisto.get(demisto.context(), 'PanOS.PolicyOptimizer.UnusedApps', [])

  data = {
      "Type": 17,
      "ContentsFormat": "number",
      "Contents": {
          "stats": len(no_apps),
          "params": {
              "layout": "horizontal",
              "name": "Rules with Unused Apps",
              "sign": "",
              "colors": {
                  "items": {
                      "#00CD33": {
                          "value": -1
                      },
                      "#FF9000": {
                          "value": 0
                      },
                      "#FF1744": {
                          "value": 3
                      }
                  }
              },
              "type": "above"
          }
      }
  }

  demisto.results(data)
scripttarget: 0
subtype: python3
tags:
- dynamic-section
type: python
