name: Review Release Notes
on: pull_request

jobs:
  release_notes_review:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content' && github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip
      - name: Install Demisto SDK
        run: pip install demisto-sdk
      - name: Get modified files
        uses: jitterbit/get-changed-files@v1
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            demisto-sdk doc-review --release-notes -i changed_file
          done
      - name: Review Release Notes
        run: demisto-sdk doc-review -g --release-notes